name: Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - run: sudo add-apt-repository ppa:deadsnakes/ppa -y
    - run: sudo apt update
    - run: make setup
    - run: make test
